### ISSUE TITLE
readme.md 示例错误

### ISSUE THREAD

**Issue by wcc4869** [itcwc/go-zhipu#3]
var t time.Duration = 60 // 请求等待时间 可不填 默认60秒

  postResponse, err := zhipu.BeCommonModel(expireAtTime, mssage, apiKey, token, t)
 

代码更新了，但是这个readme.md 里面的样例忘记更新了，应该是：

  postResponse, err := zhipu.BeCommonModel( mssage,  token, t)

**Comment by itcwc** [comment]
已修改
